# Generated by Django 5.2.12 on 2026-03-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsphaltType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название асфальта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price_per_sqm', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за кв.м (грн)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='asphalt/', verbose_name='Изображение')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на изображение (если нет файла)')),
            ],
            options={
                'verbose_name': 'Тип асфальта',
                'verbose_name_plural': 'Типы асфальта',
            },
        ),
        migrations.CreateModel(
            name='EquipmentRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название техники')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (грн)')),
                ('price_unit', models.CharField(max_length=100, verbose_name='Единица измерения (час/смена/кв.м и т.д.)')),
                ('min_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимум часов')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment/', verbose_name='Изображение')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на изображение (если нет файла)')),
            ],
            options={
                'verbose_name': 'Аренда техники',
                'verbose_name_plural': 'Аренда техники',
            },
        ),
    ]
