# Generated by Django 5.2.12 on 2026-03-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва статті')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Слаг')),
                ('short_description', models.TextField(verbose_name='Короткий опис')),
                ('full_description', models.TextField(verbose_name='Повний опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Зображення')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Посилання на зображення (якщо немає файлу)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Стаття блогу',
                'verbose_name_plural': 'Статті блогу',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.AlterModelOptions(
            name='asphalttype',
            options={'verbose_name': 'Тип асфальту', 'verbose_name_plural': 'Типи асфальту'},
        ),
        migrations.AlterModelOptions(
            name='equipmentrental',
            options={'verbose_name': 'Оренда техніки', 'verbose_name_plural': 'Оренда техніки'},
        ),
        migrations.AlterField(
            model_name='asphalttype',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='asphalttype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='asphalt/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='asphalttype',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на зображення (якщо немає файлу)'),
        ),
        migrations.AlterField(
            model_name='asphalttype',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Назва асфальту'),
        ),
        migrations.AlterField(
            model_name='asphalttype',
            name='price_per_sqm',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна за кв.м (грн)'),
        ),
        migrations.AlterField(
            model_name='equipmentrental',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='equipmentrental',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='equipmentrental',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на зображення (якщо немає файлу)'),
        ),
        migrations.AlterField(
            model_name='equipmentrental',
            name='min_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Мінімум годин'),
        ),
        migrations.AlterField(
            model_name='equipmentrental',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Назва техніки'),
        ),
        migrations.AlterField(
            model_name='equipmentrental',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна (грн)'),
        ),
        migrations.AlterField(
            model_name='equipmentrental',
            name='price_unit',
            field=models.CharField(max_length=100, verbose_name='Одиниця вимірювання (година/зміна/кв.м і т.д.)'),
        ),
    ]
