# Generated by Django 5.2.12 on 2026-03-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_blogpost_contactrequest_alter_asphalttype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ROADTECH', max_length=200, verbose_name='Назва компанії')),
                ('address', models.CharField(blank=True, max_length=400, verbose_name='Адреса')),
                ('phone_primary', models.CharField(blank=True, max_length=30, verbose_name='Телефон 1')),
                ('phone_secondary', models.CharField(blank=True, max_length=30, verbose_name='Телефон 2')),
                ('working_hours', models.CharField(blank=True, help_text='Наприклад: Пн-Пт 08:00-18:00; Сб 09:00-13:00', max_length=200, verbose_name='Графік роботи')),
                ('show_on_site', models.BooleanField(default=True, verbose_name='Показувати на сайті')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Інформація про компанію',
                'verbose_name_plural': 'Інформація про компанію',
            },
        ),
    ]
