# Generated by Django 5.2.12 on 2026-03-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_companyinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Оброблено'),
        ),
    ]
