# Generated by Django 5.2.12 on 2026-03-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_contactrequest_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок кроку')),
                ('short_description', models.CharField(max_length=255, verbose_name='Короткий опис')),
                ('full_description', models.TextField(verbose_name='Розгорнутий опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='process_steps/', verbose_name='Зображення')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Посилання на зображення')),
                ('image_alt', models.CharField(blank=True, max_length=255, verbose_name='Alt для SEO')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('featured', models.BooleanField(default=False, verbose_name='Виділений крок')),
            ],
            options={
                'verbose_name': 'Крок процесу',
                'verbose_name_plural': 'Кроки процесу',
                'ordering': ['order', 'id'],
            },
        ),
    ]
