# Generated by Django 5.2.12 on 2026-03-28 14:19

from django.db import migrations, models


def create_evacuator_defaults(apps, schema_editor):
    EvacuatorSection = apps.get_model('landing', 'EvacuatorSection')
    EvacuatorOffer = apps.get_model('landing', 'EvacuatorOffer')

    EvacuatorSection.objects.get_or_create(
        title='Евакуатор для перевезення техніки на об’єкт і окремих виїздів для авто',
        defaults={
            'eyebrow': 'Доставка техніки та евакуація',
            'description': (
                'Коли замовляють техніку для асфальтних робіт, ми допомагаємо організувати її доставку '
                'евакуатором на об’єкт. Окремо також приймаємо замовлення на евакуацію легкових авто, '
                'кросоверів, бусів і комерційного транспорту по місту та за його межами.'
            ),
            'cta_text': 'Замовити евакуатор',
            'show_on_site': True,
        },
    )

    offers = [
        {
            'order': 10,
            'name': 'Малий евакуатор',
            'subtitle': 'Швидка подача для легкових авто та компактних кросоверів',
            'description': (
                'Підходить для міських виїздів, доставки авто на СТО та акуратного завантаження '
                'машин з низькою посадкою. Також може використовуватись для локальної логістики '
                'невеликої техніки на об’єкт.'
            ),
            'price_text': 'від 3 000 грн',
            'featured': False,
            'show_on_site': True,
        },
        {
            'order': 20,
            'name': 'Великий евакуатор',
            'subtitle': 'Для важчої техніки, бусів і складних завантажень',
            'description': (
                'Потрібен, коли треба перевезти більшу техніку на об’єкт асфальтування або '
                'евакуювати комерційний транспорт. По місту від 6 000 грн, виїзд за межі міста '
                'прораховується окремо залежно від маршруту.'
            ),
            'price_text': 'від 6 000 грн',
            'featured': True,
            'show_on_site': True,
        },
        {
            'order': 30,
            'name': 'Евакуатор за місто',
            'subtitle': 'Міжміські виїзди та евакуація по області',
            'description': (
                'Якщо техніку або авто потрібно забрати з траси, селища чи сусіднього міста, '
                'погоджуємо маршрут заздалегідь і називаємо вартість до виїзду. Базова ставка '
                'по місту від 6 000 грн, за місто обговорюється окремо.'
            ),
            'price_text': '6 000 грн, за місто обговорюється',
            'featured': False,
            'show_on_site': True,
        },
    ]

    for offer in offers:
        EvacuatorOffer.objects.get_or_create(name=offer['name'], defaults=offer)


def remove_evacuator_defaults(apps, schema_editor):
    EvacuatorSection = apps.get_model('landing', 'EvacuatorSection')
    EvacuatorOffer = apps.get_model('landing', 'EvacuatorOffer')

    EvacuatorOffer.objects.filter(
        name__in=['Малий евакуатор', 'Великий евакуатор', 'Евакуатор за місто']
    ).delete()
    EvacuatorSection.objects.filter(
        title='Евакуатор для перевезення техніки на об’єкт і окремих виїздів для авто'
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_workprocessstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvacuatorOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Короткий підзаголовок')),
                ('description', models.TextField(verbose_name='Опис')),
                ('price_text', models.CharField(max_length=120, verbose_name='Текст ціни')),
                ('image', models.ImageField(blank=True, null=True, upload_to='evacuator/', verbose_name='Зображення')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Посилання на зображення')),
                ('image_alt', models.CharField(blank=True, max_length=255, verbose_name='Alt для SEO')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('featured', models.BooleanField(default=False, verbose_name='Виділити картку')),
                ('show_on_site', models.BooleanField(default=True, verbose_name='Показувати на сайті')),
            ],
            options={
                'verbose_name': 'Картка евакуатора',
                'verbose_name_plural': 'Картки евакуатора',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EvacuatorSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Доставка техніки та евакуація', max_length=120, verbose_name='Надзаголовок')),
                ('title', models.CharField(default='Евакуатор для перевезення техніки на об’єкт і окремих виїздів для авто', max_length=255, verbose_name='Заголовок секції')),
                ('description', models.TextField(default='Коли замовляють техніку для асфальтних робіт, ми допомагаємо організувати її доставку евакуатором на об’єкт. Окремо також приймаємо замовлення на евакуацію легкових авто, кросоверів, бусів і комерційного транспорту по місту та за його межами.', verbose_name='Опис секції')),
                ('cta_text', models.CharField(default='Замовити евакуатор', max_length=120, verbose_name='Текст кнопки')),
                ('show_on_site', models.BooleanField(default=True, verbose_name='Показувати на сайті')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Секція евакуатора',
                'verbose_name_plural': 'Секція евакуатора',
            },
        ),
        migrations.RunPython(create_evacuator_defaults, remove_evacuator_defaults),
    ]
